<?php

namespace App\Console\Commands;

class MedicineDataLoader
{
    protected array $templates = [];
    protected array $keywordMap = [];
    protected array $overrides = [];

    public function init(): void
    {
        $this->templates = $this->loadTemplates();
        $this->keywordMap = $this->loadKeywordMap();
        $this->overrides = $this->loadOverrides();
    }

    public function resolve(string $generic): ?array
    {
        $generic = strtolower(trim(preg_replace('/\s+/', ' ', $generic)));
        // Try stripped version (remove trailing parens like "(oral)", "(ophthalmic)")
        $key = $generic;
        if (!isset($this->overrides[$key])) {
            $stripped = preg_replace('/\s*\(.*?\)\s*$/', '', $key);
            if ($stripped !== $key) $key = $stripped;
        }
        if (isset($this->overrides[$key])) {
            $override = $this->overrides[$key];
            $classes = $override['_class'] ?? $this->classify($generic);
            if (empty($classes)) $classes = ['general'];
            $data = $this->mergeTemplate($classes);
            foreach ($override as $k => $v) {
                if ($k !== '_class') $data[$k] = $v;
            }
            return $data;
        }
        $classes = $this->classify($generic);
        if (empty($classes)) return null;
        return $this->mergeTemplate($classes);
    }

    protected function classify(string $generic): array
    {
        if (isset($this->keywordMap[$generic])) {
            $c = $this->keywordMap[$generic];
            return is_array($c) ? $c : [$c];
        }
        foreach ($this->keywordMap as $keyword => $class) {
            if (str_contains($generic, $keyword)) {
                $c = is_array($class) ? $class : [$class];
                // prefer explicit mapped generics over keyword matches
                if (isset($this->overrides[$generic])) break;
                return $c;
            }
        }
        return [];
    }

    protected function mergeTemplate(array $classes): array
    {
        $merged = [];
        foreach ($classes as $c) {
            if (isset($this->templates[$c])) {
                $t = $this->templates[$c];
                foreach ($t as $k => $v) {
                    if (!isset($merged[$k]) || empty($merged[$k])) {
                        $merged[$k] = $v;
                    }
                }
            }
        }
        return $merged;
    }

    protected function loadTemplates(): array
    {
        return [
            'antibiotic' => [
                'adult_dose' => '250-500 mg every 8 hours or as directed',
                'child_dose' => '25-50 mg/kg/day in divided doses',
                'max_daily_dose' => '4000 mg',
                'duration_recommendation' => '5-14 days as prescribed',
                'side_effects' => 'Nausea, diarrhea, abdominal pain, rash',
                'contraindications' => 'Hypersensitivity to this drug class',
                'pregnancy_safe' => 'Consult physician; use only if clearly needed',
                'allergy_warning' => 'Allergic reactions including rash, itching, swelling; seek immediate medical help if severe',
                'drug_interaction_notes' => 'May reduce effectiveness of oral contraceptives; monitor warfarin',
                'usage_instructions' => 'Take at evenly spaced intervals; complete full course even if feeling better',
                'food_interaction' => 'Some formulations take with food to reduce GI upset; check specific medicine',
                'alcohol_warning' => 'Avoid alcohol; may increase side effects or reduce effectiveness',
            ],
            'cephalosporin' => [
                'adult_dose' => '250-500 mg every 8-12 hours',
                'child_dose' => '25-100 mg/kg/day in divided doses',
                'max_daily_dose' => '4000 mg',
                'duration_recommendation' => '5-14 days depending on infection severity',
                'side_effects' => 'Diarrhea, nausea, rash, injection site reactions',
                'contraindications' => 'Known hypersensitivity to cephalosporins; caution with penicillin allergy',
                'pregnancy_safe' => 'Generally considered safe; consult physician',
                'allergy_warning' => 'Cross-sensitivity with penicillins possible; discontinue if rash or difficulty breathing occurs',
                'drug_interaction_notes' => 'May increase nephrotoxicity with aminoglycosides; may affect warfarin metabolism',
                'usage_instructions' => 'Take with or without food; complete prescribed course',
                'food_interaction' => 'Take with food if stomach upset occurs',
                'alcohol_warning' => 'Avoid alcohol during treatment and for 72 hours after last dose (disulfiram-like reaction)',
            ],
            'fluoroquinolone' => [
                'adult_dose' => '250-750 mg once or twice daily',
                'child_dose' => 'Not recommended in children (cartilage damage risk)',
                'max_daily_dose' => '1500 mg',
                'duration_recommendation' => '5-14 days depending on infection',
                'side_effects' => 'Nausea, diarrhea, dizziness, headache, tendonitis',
                'contraindications' => 'History of tendon disorders with fluoroquinolones; epilepsy; myasthenia gravis',
                'pregnancy_safe' => 'Avoid during pregnancy and lactation',
                'allergy_warning' => 'Serious allergic reactions possible; discontinue if rash, hives, or breathing difficulty occurs',
                'drug_interaction_notes' => 'Avoid NSAIDs (increased CNS effects); may prolong QTc; avoid with class III antiarrhythmics',
                'usage_instructions' => 'Take with plenty of water; avoid excessive sunlight/UV exposure',
                'food_interaction' => 'Avoid dairy products, antacids, iron supplements within 2-4 hours of dose',
                'alcohol_warning' => 'Avoid alcohol; may increase CNS side effects',
            ],
            'macrolide' => [
                'adult_dose' => '250-500 mg once or twice daily',
                'child_dose' => '15-50 mg/kg/day in divided doses',
                'max_daily_dose' => '2000 mg',
                'duration_recommendation' => '3-14 days depending on infection',
                'side_effects' => 'Nausea, vomiting, abdominal pain, diarrhea, metallic taste',
                'contraindications' => 'Hypersensitivity; caution in hepatic impairment',
                'pregnancy_safe' => 'Generally safe in pregnancy; consult physician',
                'allergy_warning' => 'Allergic reactions including rash, urticaria, angioedema',
                'drug_interaction_notes' => 'May increase levels of warfarin, theophylline, digoxin, statins; avoid with pimozide, ergotamine',
                'usage_instructions' => 'Take as directed; some formulations with food, others on empty stomach',
                'food_interaction' => 'Check specific medicine; some require empty stomach, others with food',
                'alcohol_warning' => 'Avoid alcohol; may worsen GI side effects',
            ],
            'aminoglycoside' => [
                'adult_dose' => '3-5 mg/kg/day in divided doses (parenteral)',
                'child_dose' => '5-7.5 mg/kg/day in divided doses',
                'max_daily_dose' => '15 mg/kg',
                'duration_recommendation' => '7-10 days; monitor renal function',
                'side_effects' => 'Nephrotoxicity, ototoxicity, dizziness, nausea',
                'contraindications' => 'Myasthenia gravis; caution in renal impairment',
                'pregnancy_safe' => 'Avoid during pregnancy unless absolutely necessary',
                'allergy_warning' => 'Allergic reactions possible; report hearing changes or dizziness',
                'drug_interaction_notes' => 'Increased nephrotoxicity with cephalosporins, vancomycin, loop diuretics',
                'usage_instructions' => 'Usually administered by injection; ensure adequate hydration',
                'food_interaction' => 'No significant food interactions',
                'alcohol_warning' => 'Avoid alcohol; may increase dizziness',
            ],
            'tetracycline' => [
                'adult_dose' => '250-500 mg every 6-12 hours',
                'child_dose' => 'Not recommended in children under 8 years (teeth discoloration)',
                'max_daily_dose' => '2000 mg',
                'duration_recommendation' => '7-21 days depending on condition',
                'side_effects' => 'Photosensitivity, GI upset, teeth discoloration, yeast infections',
                'contraindications' => 'Children under 8 years; pregnancy; lactation; hepatic impairment',
                'pregnancy_safe' => 'Avoid during pregnancy (fetal harm)',
                'allergy_warning' => 'Photosensitivity reactions; discontinue if severe skin reaction occurs',
                'drug_interaction_notes' => 'Avoid dairy, antacids, iron, calcium supplements within 2-3 hours; may increase warfarin effect',
                'usage_instructions' => 'Take on empty stomach with full glass of water; avoid lying down after dose',
                'food_interaction' => 'Avoid dairy products, calcium-fortified foods within 2-3 hours of dose',
                'alcohol_warning' => 'Avoid alcohol; may worsen GI side effects',
            ],
            'antifungal' => [
                'adult_dose' => '100-400 mg daily depending on specific medicine',
                'child_dose' => '3-12 mg/kg/day depending on specific medicine',
                'max_daily_dose' => '800 mg',
                'duration_recommendation' => '7-28 days or longer depending on infection',
                'side_effects' => 'Nausea, abdominal pain, headache, elevated liver enzymes',
                'contraindications' => 'Severe hepatic impairment; hypersensitivity',
                'pregnancy_safe' => 'Avoid during pregnancy (especially first trimester) unless essential',
                'allergy_warning' => 'Allergic reactions including rash, pruritus; discontinue if jaundice occurs',
                'drug_interaction_notes' => 'Many drug interactions; monitor warfarin, oral hypoglycemics, statins, antiepileptics',
                'usage_instructions' => 'Take with food to improve absorption; complete full course',
                'food_interaction' => 'Take with food for better absorption; avoid grapefruit juice (some azoles)',
                'alcohol_warning' => 'Avoid alcohol; hepatotoxicity risk and disulfiram-like reaction',
            ],
            'ppi' => [
                'adult_dose' => '20-40 mg once or twice daily',
                'child_dose' => '0.5-1 mg/kg once daily',
                'max_daily_dose' => '80 mg',
                'duration_recommendation' => '4-8 weeks; long-term use requires medical supervision',
                'side_effects' => 'Headache, nausea, diarrhea, flatulence, constipation',
                'contraindications' => 'Concurrent use with rilpivirine; severe hypomagnesemia',
                'pregnancy_safe' => 'Generally considered safe; consult physician',
                'allergy_warning' => 'Rare allergic reactions including rash, urticaria, angioedema',
                'drug_interaction_notes' => 'May reduce absorption of ketoconazole, itraconazole, iron, vitamin B12; may increase methotrexate levels',
                'usage_instructions' => 'Take 30-60 minutes before meals, preferably morning before breakfast',
                'food_interaction' => 'Take on empty stomach before meals for best effect',
                'alcohol_warning' => 'Moderate alcohol generally acceptable but may worsen symptoms',
            ],
            'h2antagonist' => [
                'adult_dose' => '150-300 mg once or twice daily',
                'child_dose' => '2-5 mg/kg twice daily',
                'max_daily_dose' => '600 mg',
                'duration_recommendation' => '4-12 weeks as directed',
                'side_effects' => 'Headache, dizziness, diarrhea, constipation, fatigue',
                'contraindications' => 'Hypersensitivity; severe renal impairment (dose adjustment needed)',
                'pregnancy_safe' => 'Generally considered safe; consult physician',
                'allergy_warning' => 'Rare allergic reactions; discontinue if rash or difficulty breathing',
                'drug_interaction_notes' => 'May reduce absorption of drugs requiring acidic pH; monitor warfarin, theophylline',
                'usage_instructions' => 'Take with or without food; take at bedtime for nocturnal symptoms',
                'food_interaction' => 'Take with food if stomach upset occurs',
                'alcohol_warning' => 'Limit alcohol; may increase stomach irritation',
            ],
            'antacid' => [
                'adult_dose' => '10-20 mL or 1-2 tablets as needed after meals and at bedtime',
                'child_dose' => '5-10 mL as needed (age dependent)',
                'max_daily_dose' => 'As directed on package; not to exceed 7 days continuous use',
                'duration_recommendation' => 'Short-term relief only; not for chronic use without medical advice',
                'side_effects' => 'Constipation (aluminum-based), diarrhea (magnesium-based)',
                'contraindications' => 'Severe renal impairment; caution with low phosphate diets',
                'pregnancy_safe' => 'Generally safe in standard doses; consult physician',
                'allergy_warning' => 'Rare allergic reactions',
                'drug_interaction_notes' => 'May reduce absorption of tetracyclines, fluoroquinolones, iron, digoxin, thyroid hormones',
                'usage_instructions' => 'Chew thoroughly or shake suspension well; take 1-3 hours apart from other medications',
                'food_interaction' => 'Take 1 hour after meals and at bedtime',
                'alcohol_warning' => 'Limit alcohol; may worsen acid reflux',
            ],
            'painkiller_nsaid' => [
                'adult_dose' => '200-800 mg every 6-8 hours as needed',
                'child_dose' => '5-10 mg/kg every 6-8 hours',
                'max_daily_dose' => '2400 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term use (3-7 days) unless directed otherwise',
                'side_effects' => 'Stomach upset, heartburn, nausea, headache, dizziness, fluid retention',
                'contraindications' => 'Active peptic ulcer; severe renal/hepatic impairment; history of GI bleeding',
                'pregnancy_safe' => 'Avoid in third trimester; use caution in first two trimesters',
                'allergy_warning' => 'Allergic reactions including asthma exacerbation, rash, angioedema; avoid if allergic to aspirin',
                'drug_interaction_notes' => 'Avoid with anticoagulants (increased bleeding); may reduce effect of diuretics, ACE inhibitors',
                'usage_instructions' => 'Take with food or milk to reduce GI upset; use lowest effective dose for shortest duration',
                'food_interaction' => 'Take with food to minimize stomach irritation',
                'alcohol_warning' => 'Avoid or limit alcohol; increased risk of GI bleeding',
            ],
            'painkiller_paracetamol' => [
                'adult_dose' => '500-1000 mg every 4-6 hours as needed',
                'child_dose' => '10-15 mg/kg every 4-6 hours',
                'max_daily_dose' => '4000 mg (3000 mg if hepatic risk)',
                'duration_recommendation' => 'Short-term use (3-5 days); consult physician if longer needed',
                'side_effects' => 'Generally well-tolerated; rare rash, nausea',
                'contraindications' => 'Severe hepatic impairment; hypersensitivity',
                'pregnancy_safe' => 'Generally considered safe in standard doses',
                'allergy_warning' => 'Rare allergic reactions including rash, angioedema',
                'drug_interaction_notes' => 'May increase warfarin effect with prolonged use; avoid other paracetamol-containing products',
                'usage_instructions' => 'Do not exceed recommended dose; take with water',
                'food_interaction' => 'Can be taken with or without food',
                'alcohol_warning' => 'Avoid or limit alcohol; increased hepatotoxicity risk',
            ],
            'opioid' => [
                'adult_dose' => 'Dose varies by specific opioid and pain severity; follow prescription exactly',
                'child_dose' => 'Weight-based dosing; use only under strict medical supervision',
                'max_daily_dose' => 'Varies by specific drug; follow prescription',
                'duration_recommendation' => 'Short-term use (3-7 days) for acute pain; chronic use requires careful monitoring',
                'side_effects' => 'Drowsiness, constipation, nausea, vomiting, dizziness, respiratory depression',
                'contraindications' => 'Respiratory depression; acute asthma; paralytic ileus; MAOI use',
                'pregnancy_safe' => 'Avoid during pregnancy; neonatal withdrawal syndrome risk',
                'allergy_warning' => 'Allergic reactions including rash, urticaria; seek emergency help if breathing difficulty',
                'drug_interaction_notes' => 'Avoid with alcohol, benzodiazepines, other CNS depressants (fatal respiratory depression); MAOI interaction risk',
                'usage_instructions' => 'Take exactly as prescribed; do not crush or chew extended-release formulations',
                'food_interaction' => 'Take with or without food; high-fat meal may delay absorption',
                'alcohol_warning' => 'Avoid alcohol completely; risk of severe respiratory depression and death',
            ],
            'corticosteroid' => [
                'adult_dose' => '5-60 mg daily depending on condition (varies by specific drug)',
                'child_dose' => '0.14-2 mg/kg/day depending on condition',
                'max_daily_dose' => 'Varies significantly by specific drug and condition',
                'duration_recommendation' => 'Short-term: 3-14 days; long-term: taper under medical supervision',
                'side_effects' => 'Increased appetite, weight gain, fluid retention, mood changes, insomnia, elevated blood sugar',
                'contraindications' => 'Systemic fungal infections; live vaccine administration; caution in diabetes, hypertension',
                'pregnancy_safe' => 'Use if clearly needed; benefits vs risks assessment required',
                'allergy_warning' => 'Allergic reactions rare; may mask signs of infection',
                'drug_interaction_notes' => 'May decrease effect of antidiabetics, antihypertensives; increased GI bleeding risk with NSAIDs',
                'usage_instructions' => 'Take with food to reduce GI upset; do not stop abruptly; taper dose as directed',
                'food_interaction' => 'Take with food to minimize stomach irritation; avoid high-sodium foods',
                'alcohol_warning' => 'Limit or avoid alcohol; increased GI irritation risk',
            ],
            'antihistamine' => [
                'adult_dose' => '10 mg once daily (varies by specific drug)',
                'child_dose' => '5-10 mg once daily (age dependent)',
                'max_daily_dose' => '20 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term for allergies; long-term use under medical supervision',
                'side_effects' => 'Drowsiness (first generation), dry mouth, headache, fatigue',
                'contraindications' => 'Severe hepatic impairment; caution in glaucoma, urinary retention, prostatic hyperplasia',
                'pregnancy_safe' => 'Generally safe; consult physician (especially first generation)',
                'allergy_warning' => 'Allergic reactions possible; discontinue if rash or breathing difficulty',
                'drug_interaction_notes' => 'Avoid alcohol, sedatives, tranquilizers (increased drowsiness); may affect MAOIs',
                'usage_instructions' => 'Take in evening if drowsiness occurs; non-sedating types take once daily in morning',
                'food_interaction' => 'Can be taken with or without food',
                'alcohol_warning' => 'Avoid alcohol; increased drowsiness and impairment',
            ],
            'antidiabetic_biguanide' => [
                'adult_dose' => '500-2000 mg daily in divided doses',
                'child_dose' => 'Not recommended in children (unless specific indication)',
                'max_daily_dose' => '2550 mg',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Nausea, diarrhea, metallic taste, decreased appetite, lactic acidosis (rare)',
                'contraindications' => 'Severe renal impairment; hepatic impairment; metabolic acidosis; heart failure',
                'pregnancy_safe' => 'Consult physician; insulin preferred during pregnancy',
                'allergy_warning' => 'Rare allergic reactions; discontinue if rash or breathing difficulty',
                'drug_interaction_notes' => 'Avoid alcohol (increased lactic acidosis risk); monitor with contrast dye procedures',
                'usage_instructions' => 'Take with meals to reduce GI side effects; monitor blood glucose regularly',
                'food_interaction' => 'Take with meals to minimize GI upset',
                'alcohol_warning' => 'Avoid excessive alcohol; increased risk of lactic acidosis and hypoglycemia',
            ],
            'antidiabetic_sulfonylurea' => [
                'adult_dose' => '2.5-20 mg daily depending on specific drug',
                'child_dose' => 'Not typically recommended in children',
                'max_daily_dose' => 'Varies by specific drug (e.g., glibenclamide 20 mg)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Hypoglycemia, weight gain, nausea, skin reactions',
                'contraindications' => 'Type 1 diabetes; severe hepatic/renal impairment; ketosis-prone diabetes',
                'pregnancy_safe' => 'Consult physician; insulin preferred during pregnancy',
                'allergy_warning' => 'Allergic skin reactions possible; discontinue if severe rash',
                'drug_interaction_notes' => 'Increased hypoglycemia risk with alcohol, NSAIDs, warfarin, MAOIs; decreased effect with thiazides, corticosteroids',
                'usage_instructions' => 'Take 30 minutes before meals; monitor blood glucose regularly',
                'food_interaction' => 'Take before meals for optimal blood glucose control',
                'alcohol_warning' => 'Avoid alcohol; may cause disulfiram-like reaction and increased hypoglycemia risk',
            ],
            'antidiabetic_dpp4' => [
                'adult_dose' => '100 mg once daily (varies by specific drug)',
                'child_dose' => 'Not established in children',
                'max_daily_dose' => '100 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Upper respiratory infection, headache, nausea, joint pain',
                'contraindications' => 'Type 1 diabetes; diabetic ketoacidosis; severe renal impairment',
                'pregnancy_safe' => 'Consult physician; insulin preferred during pregnancy',
                'allergy_warning' => 'Rare angioedema and allergic reactions; discontinue if severe reaction',
                'drug_interaction_notes' => 'Few significant drug interactions; monitor with sulfonylureas (hypoglycemia risk)',
                'usage_instructions' => 'Take once daily with or without food',
                'food_interaction' => 'Can be taken with or without food',
                'alcohol_warning' => 'Moderate alcohol generally acceptable; monitor blood glucose',
            ],
            'antidiabetic_insulin' => [
                'adult_dose' => 'Individualized dosing; typically 0.5-1 unit/kg/day',
                'child_dose' => 'Individualized diabetes management required',
                'max_daily_dose' => 'Individualized; as directed by physician',
                'duration_recommendation' => 'Long-term maintenance; do not discontinue without medical advice',
                'side_effects' => 'Hypoglycemia, injection site reactions, weight gain, edema',
                'contraindications' => 'Hypoglycemia; hypersensitivity to specific insulin type',
                'pregnancy_safe' => 'Essential for diabetes management during pregnancy; dose adjustment needed',
                'allergy_warning' => 'Local allergic reactions at injection site; rare systemic allergic reactions',
                'drug_interaction_notes' => 'Many drugs affect blood glucose; monitor closely with beta-blockers, corticosteroids, thyroid hormones',
                'usage_instructions' => 'Rotate injection sites; follow prescribed dosing schedule; monitor blood glucose',
                'food_interaction' => 'Coordinate meals with insulin timing',
                'alcohol_warning' => 'Avoid or limit alcohol; increased hypoglycemia risk',
            ],
            'antihypertensive_ace' => [
                'adult_dose' => '2.5-40 mg daily (varies by specific drug)',
                'child_dose' => '0.05-0.6 mg/kg once daily',
                'max_daily_dose' => '40 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Dry persistent cough, dizziness, headache, hyperkalemia, hypotension',
                'contraindications' => 'Pregnancy; history of angioedema; bilateral renal artery stenosis',
                'pregnancy_safe' => 'Avoid during pregnancy (fetal harm)',
                'allergy_warning' => 'Angioedema (swelling of face, lips, throat); seek emergency help if occurs',
                'drug_interaction_notes' => 'Increased hyperkalemia with potassium supplements, K-sparing diuretics; may increase lithium levels',
                'usage_instructions' => 'Take at same time daily; monitor blood pressure regularly',
                'food_interaction' => 'Can be taken with or without food; avoid high-potassium foods',
                'alcohol_warning' => 'Limit alcohol; may increase BP-lowering effect and dizziness',
            ],
            'antihypertensive_arb' => [
                'adult_dose' => '25-300 mg daily (varies by specific drug)',
                'child_dose' => 'Weight-based dosing; consult physician',
                'max_daily_dose' => '300 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Dizziness, headache, hyperkalemia, hypotension, renal impairment',
                'contraindications' => 'Pregnancy; bilateral renal artery stenosis; severe hepatic impairment',
                'pregnancy_safe' => 'Avoid during pregnancy (fetal harm)',
                'allergy_warning' => 'Rare angioedema; discontinue if swelling of face or throat occurs',
                'drug_interaction_notes' => 'Increased hyperkalemia with potassium supplements, K-sparing diuretics; may increase lithium levels',
                'usage_instructions' => 'Take at same time daily; monitor blood pressure regularly',
                'food_interaction' => 'Can be taken with or without food',
                'alcohol_warning' => 'Limit alcohol; may increase BP-lowering effect',
            ],
            'antihypertensive_ccb' => [
                'adult_dose' => '30-120 mg daily (varies by specific drug)',
                'child_dose' => '0.15-0.5 mg/kg/day (limited data)',
                'max_daily_dose' => '120 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Dizziness, flushing, headache, peripheral edema, constipation, palpitations',
                'contraindications' => 'Severe hypotension; cardiogenic shock; sick sinus syndrome; second/third degree AV block',
                'pregnancy_safe' => 'Avoid during pregnancy unless clearly needed',
                'allergy_warning' => 'Rare allergic reactions including rash, pruritus',
                'drug_interaction_notes' => 'Avoid grapefruit juice (increases drug levels); increase digoxin, simvastatin levels; may potentiate beta-blockers',
                'usage_instructions' => 'Take at same time daily; avoid grapefruit juice; monitor BP',
                'food_interaction' => 'Avoid grapefruit juice; take with or without food',
                'alcohol_warning' => 'Limit alcohol; may increase BP-lowering effect and dizziness',
            ],
            'betablocker' => [
                'adult_dose' => '25-100 mg daily (varies by specific drug)',
                'child_dose' => '0.5-2 mg/kg/day (limited data)',
                'max_daily_dose' => '400 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; do not discontinue abruptly',
                'side_effects' => 'Fatigue, dizziness, bradycardia, cold extremities, sleep disturbances, mask hypoglycemia symptoms',
                'contraindications' => 'Severe bradycardia; heart block; cardiogenic shock; uncontrolled heart failure; asthma',
                'pregnancy_safe' => 'Use if clearly needed; may cause fetal bradycardia',
                'allergy_warning' => 'Rare allergic reactions; may mask allergy symptoms',
                'drug_interaction_notes' => 'Avoid verapamil, diltiazem (heart block risk); increased bradycardia with digoxin; may mask hypoglycemia symptoms',
                'usage_instructions' => 'Take at same time daily; do not stop abruptly (rebound hypertension risk)',
                'food_interaction' => 'Take with or without food; be consistent with timing',
                'alcohol_warning' => 'Limit alcohol; may increase BP-lowering effect',
            ],
            'statin' => [
                'adult_dose' => '10-80 mg once daily (varies by specific drug)',
                'child_dose' => 'Limited use in children; consult specialist',
                'max_daily_dose' => '80 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Muscle pain, headache, nausea, elevated liver enzymes, rarely rhabdomyolysis',
                'contraindications' => 'Active liver disease; pregnancy; lactation; caution with unexplained elevated transaminases',
                'pregnancy_safe' => 'Avoid during pregnancy and breastfeeding',
                'allergy_warning' => 'Rare allergic reactions; report unexplained muscle pain, tenderness, or weakness',
                'drug_interaction_notes' => 'Avoid grapefruit juice (some statins); increased myopathy risk with fibrates, erythromycin, azole antifungals, cyclosporine',
                'usage_instructions' => 'Take in evening (some statins); monitor liver enzymes and lipid profile regularly',
                'food_interaction' => 'Avoid grapefruit juice (atorvastatin, simvastatin, lovastatin); some statins take with food',
                'alcohol_warning' => 'Limit alcohol; increased liver damage risk',
            ],
            'bronchodilator' => [
                'adult_dose' => '1-2 inhalations every 4-6 hours as needed',
                'child_dose' => '1 inhalation every 4-6 hours (age dependent)',
                'max_daily_dose' => 'As directed on package or by physician',
                'duration_recommendation' => 'Short-term relief; long-term maintenance under medical supervision',
                'side_effects' => 'Tremor, palpitations, headache, dizziness, dry mouth',
                'contraindications' => 'Hypersensitivity; caution in cardiac arrhythmias, hypertension, hyperthyroidism',
                'pregnancy_safe' => 'Generally safe for asthma management; consult physician',
                'allergy_warning' => 'Rare allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Increased cardiac effects with MAOIs, TCAs; may be potentiated by beta-blockers',
                'usage_instructions' => 'Shake inhaler well before use; inhale deeply and hold breath; rinse mouth after use (steroids)',
                'food_interaction' => 'No significant food interactions',
                'alcohol_warning' => 'Limit alcohol; may worsen underlying condition',
            ],
            'leukotriene' => [
                'adult_dose' => '10 mg once daily in the evening',
                'child_dose' => '4-5 mg once daily (age dependent)',
                'max_daily_dose' => '10 mg',
                'duration_recommendation' => 'Long-term maintenance for asthma/allergic rhinitis',
                'side_effects' => 'Headache, abdominal pain, thirst, mild elevated liver enzymes',
                'contraindications' => 'Hypersensitivity; caution in hepatic impairment',
                'pregnancy_safe' => 'Use if clearly needed; consult physician',
                'allergy_warning' => 'Eosinophilic granulomatosis with polyangiitis (rare); report rash, numbness, or flu-like symptoms',
                'drug_interaction_notes' => 'May decrease effect with phenobarbital, rifampin; few significant interactions',
                'usage_instructions' => 'Take in evening; may take with or without food',
                'food_interaction' => 'Can be taken with or without food; take granules with soft foods',
                'alcohol_warning' => 'Moderate alcohol generally acceptable',
            ],
            'antiepileptic' => [
                'adult_dose' => '200-2000 mg daily depending on specific drug',
                'child_dose' => 'Weight-based dosing; consult physician',
                'max_daily_dose' => 'Varies by specific drug (up to 4000 mg for some)',
                'duration_recommendation' => 'Long-term maintenance; do not discontinue abruptly',
                'side_effects' => 'Drowsiness, dizziness, ataxia, nausea, rash, weight changes',
                'contraindications' => 'Hypersensitivity; caution in hepatic/renal impairment; specific contraindications vary by drug',
                'pregnancy_safe' => 'Consult physician; risk of birth defects but uncontrolled seizures also harmful',
                'allergy_warning' => 'Severe allergic reactions including Stevens-Johnson syndrome (rare); report rash immediately',
                'drug_interaction_notes' => 'Many drug interactions; affects oral contraceptives, warfarin, other antiepileptics; monitor levels',
                'usage_instructions' => 'Take consistently at same times; do not skip doses; monitor blood levels if required',
                'food_interaction' => 'Take with food if GI upset occurs',
                'alcohol_warning' => 'Avoid or limit alcohol; may lower seizure threshold and increase side effects',
            ],
            'antidepressant_ssri' => [
                'adult_dose' => '20-60 mg once daily (varies by specific drug)',
                'child_dose' => 'Limited use; weight-based dosing under specialist supervision',
                'max_daily_dose' => '60-80 mg (varies by specific drug)',
                'duration_recommendation' => 'Months to years; continue as directed even after improvement',
                'side_effects' => 'Nausea, insomnia, drowsiness, sexual dysfunction, weight changes, dry mouth',
                'contraindications' => 'MAOI use within 14 days; caution in bipolar disorder, epilepsy, hepatic impairment',
                'pregnancy_safe' => 'Consult physician; risk of persistent pulmonary hypertension in newborn (small risk)',
                'allergy_warning' => 'Allergic reactions including rash, urticaria; serotonin syndrome (rare: agitation, fever, muscle rigidity)',
                'drug_interaction_notes' => 'Do not use with MAOIs; increased serotonergic effects with tramadol, triptans, St. John\'s Wort; increased bleeding with NSAIDs, warfarin',
                'usage_instructions' => 'Take at same time daily; may take weeks for full effect; do not stop abruptly',
                'food_interaction' => 'Take with or without food',
                'alcohol_warning' => 'Avoid alcohol; may worsen depression and increase side effects',
            ],
            'antidepressant_tca' => [
                'adult_dose' => '25-150 mg daily (varies by specific drug)',
                'child_dose' => 'Limited use; weight-based dosing under specialist supervision',
                'max_daily_dose' => '300 mg (varies by specific drug)',
                'duration_recommendation' => 'Months to years; continue as directed',
                'side_effects' => 'Drowsiness, dry mouth, blurred vision, constipation, urinary retention, weight gain, orthostatic hypotension',
                'contraindications' => 'Recent MI; heart block; MAOI use within 14 days; narrow-angle glaucoma; urinary retention',
                'pregnancy_safe' => 'Consult physician; risk assessment needed',
                'allergy_warning' => 'Allergic reactions including rash, photosensitivity; rare blood dyscrasias',
                'drug_interaction_notes' => 'Many interactions; increased sedation with alcohol, benzodiazepines; increased arrhythmia risk with antiarrhythmics; MAOI interaction risk',
                'usage_instructions' => 'Take in evening (if drowsiness occurs); take with food if GI upset; do not stop abruptly',
                'food_interaction' => 'Take with food if GI upset occurs',
                'alcohol_warning' => 'Avoid alcohol; increased sedation and CNS depression',
            ],
            'antipsychotic' => [
                'adult_dose' => '2-20 mg daily (varies significantly by specific drug)',
                'child_dose' => 'Limited use; specialist supervision required',
                'max_daily_dose' => 'Varies significantly by specific drug',
                'duration_recommendation' => 'Long-term maintenance under psychiatric supervision',
                'side_effects' => 'Drowsiness, weight gain, dry mouth, constipation, extrapyramidal symptoms, metabolic changes',
                'contraindications' => 'Comatose states; CNS depression; specific contraindications vary by drug',
                'pregnancy_safe' => 'Consult physician; risk assessment needed',
                'allergy_warning' => 'Allergic reactions including rash, photosensitivity; neuroleptic malignant syndrome (rare: fever, rigidity, confusion)',
                'drug_interaction_notes' => 'Increased sedation with alcohol, benzodiazepines; may prolong QTc (avoid with other QTc-prolonging drugs); CYP interactions vary',
                'usage_instructions' => 'Take as directed at same times daily; do not stop abruptly',
                'food_interaction' => 'Take with or without food',
                'alcohol_warning' => 'Avoid alcohol; increased sedation and CNS depression',
            ],
            'benzodiazepine' => [
                'adult_dose' => '2-20 mg daily depending on specific drug and indication',
                'child_dose' => 'Limited use; lowest effective dose under specialist supervision',
                'max_daily_dose' => 'Varies by specific drug',
                'duration_recommendation' => 'Short-term use (2-4 weeks) due to dependence risk',
                'side_effects' => 'Drowsiness, dizziness, ataxia, confusion, dependence, memory impairment',
                'contraindications' => 'Myasthenia gravis; severe hepatic impairment; sleep apnea; respiratory insufficiency; addiction history',
                'pregnancy_safe' => 'Avoid during pregnancy (especially first and third trimesters); neonatal withdrawal risk',
                'allergy_warning' => 'Rare allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Increased CNS depression with alcohol, opioids, other sedatives; may increase digoxin levels',
                'usage_instructions' => 'Take exactly as prescribed; short-term use only; taper when discontinuing',
                'food_interaction' => 'Take with food if GI upset occurs',
                'alcohol_warning' => 'Avoid alcohol completely; severe sedation, respiratory depression, and death risk',
            ],
            'anticoagulant' => [
                'adult_dose' => 'Varies by specific drug; warfarin 2-10 mg daily adjusted by INR; DOACs fixed dose',
                'child_dose' => 'Weight-based dosing under specialist supervision',
                'max_daily_dose' => 'Therapeutic range dependent on INR for warfarin; fixed for DOACs',
                'duration_recommendation' => 'As directed by physician; may be short-term or long-term',
                'side_effects' => 'Bleeding, bruising, anemia, nausea, rash (warfarin)',
                'contraindications' => 'Active bleeding; hemorrhagic disorders; recent surgery; uncontrolled hypertension; pregnancy (warfarin)',
                'pregnancy_safe' => 'Avoid warfarin during pregnancy; DOACs not recommended; consult physician',
                'allergy_warning' => 'Rash, itching, necrosis (warfarin); report unusual bleeding or bruising',
                'drug_interaction_notes' => 'Many drug interactions; food interactions with warfarin (vitamin K); monitor INR regularly; avoid NSAIDs',
                'usage_instructions' => 'Take at same time daily; regular blood monitoring required (warfarin); carry medication alert card',
                'food_interaction' => 'Warfarin: maintain consistent vitamin K intake; avoid cranberry juice, grapefruit juice',
                'alcohol_warning' => 'Limit alcohol; increased bleeding risk; may affect INR',
            ],
            'antiplatelet' => [
                'adult_dose' => '75-325 mg once daily (varies by specific drug)',
                'child_dose' => 'Limited use; weight-based dosing under specialist supervision',
                'max_daily_dose' => '325 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Bleeding, bruising, GI upset, nausea, diarrhea',
                'contraindications' => 'Active bleeding; severe hepatic impairment; active peptic ulcer; hypersensitivity',
                'pregnancy_safe' => 'Use if clearly needed; avoid in third trimester (aspirin)',
                'allergy_warning' => 'Allergic reactions including rash, urticaria; aspirin: avoid if nasal polyps or asthma',
                'drug_interaction_notes' => 'Increased bleeding risk with anticoagulants, NSAIDs, SSRIs; avoid with methotrexate (aspirin)',
                'usage_instructions' => 'Take at same time daily; with or without food; inform all healthcare providers before procedures',
                'food_interaction' => 'Enteric-coated formulations reduce GI upset; take with food',
                'alcohol_warning' => 'Limit alcohol; increased GI bleeding risk',
            ],
            'diuretic' => [
                'adult_dose' => '25-100 mg daily (varies by specific drug)',
                'child_dose' => '1-4 mg/kg/day (varies by specific drug)',
                'max_daily_dose' => '200 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance or short-term as directed',
                'side_effects' => 'Frequent urination, electrolyte imbalances, dizziness, dehydration, muscle cramps',
                'contraindications' => 'Anuria; severe renal failure; severe electrolyte depletion; hepatic coma',
                'pregnancy_safe' => 'Use if clearly needed; monitor closely',
                'allergy_warning' => 'Rash, photosensitivity (thiazides); sulfonamide allergy cross-reactivity (thiazides, loop)',
                'drug_interaction_notes' => 'Increased hypokalemia with corticosteroids, amphotericin B; decreased effect with NSAIDs; increased digoxin toxicity (hypokalemia)',
                'usage_instructions' => 'Take in morning to avoid nighttime urination; monitor weight and electrolytes',
                'food_interaction' => 'Take with food to reduce GI upset; avoid high-sodium foods',
                'alcohol_warning' => 'Limit alcohol; may increase dehydration and BP-lowering effect',
            ],
            'antiemetic' => [
                'adult_dose' => '10-20 mg every 6-8 hours as needed (varies by specific drug)',
                'child_dose' => '0.15-0.3 mg/kg every 6-8 hours',
                'max_daily_dose' => '80 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term use (1-3 days) unless directed otherwise',
                'side_effects' => 'Drowsiness, dry mouth, dizziness, headache, extrapyramidal symptoms (some)',
                'contraindications' => 'Hypersensitivity; GI obstruction; caution in Parkinsonism (some)',
                'pregnancy_safe' => 'Some safe in pregnancy (e.g., ondansetron); consult physician',
                'allergy_warning' => 'Allergic reactions including rash, urticaria; extrapyramidal symptoms (report involuntary muscle movements)',
                'drug_interaction_notes' => 'Increased sedation with alcohol, benzodiazepines; serotonergic effects with SSRIs (ondansetron)',
                'usage_instructions' => 'Take before nausea becomes severe; may be taken with or without food',
                'food_interaction' => 'Take with food if stomach upset occurs',
                'alcohol_warning' => 'Avoid alcohol; increased drowsiness and dizziness',
            ],
            'antispasmodic' => [
                'adult_dose' => '10-20 mg every 6-8 hours as needed',
                'child_dose' => 'Weight-based dosing; consult physician',
                'max_daily_dose' => '80 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term use for acute symptoms',
                'side_effects' => 'Dry mouth, blurred vision, dizziness, constipation, urinary retention',
                'contraindications' => 'Glaucoma; myasthenia gravis; urinary retention; GI obstruction; severe ulcerative colitis',
                'pregnancy_safe' => 'Consult physician; use if clearly needed',
                'allergy_warning' => 'Allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Increased anticholinergic effects with TCAs, antihistamines, antipsychotics',
                'usage_instructions' => 'Take 30-60 minutes before meals for GI cramping; take with or without food',
                'food_interaction' => 'Can be taken with or without food',
                'alcohol_warning' => 'Avoid alcohol; increased drowsiness and dizziness',
            ],
            'vitamin' => [
                'adult_dose' => 'As directed on package or by physician',
                'child_dose' => 'Age-appropriate dosing as directed',
                'max_daily_dose' => 'Varies by specific vitamin; follow recommended dietary allowance',
                'duration_recommendation' => 'As directed; long-term supplementation under medical advice',
                'side_effects' => 'Generally well-tolerated; high doses may cause GI upset, nausea',
                'contraindications' => 'Specific contraindications vary; hypervitaminosis for fat-soluble vitamins',
                'pregnancy_safe' => 'Most safe at recommended doses; prenatal vitamins recommended',
                'allergy_warning' => 'Rare allergic reactions; some formulations contain allergens',
                'drug_interaction_notes' => 'Varies by specific vitamin; vitamin K may affect warfarin; calcium affects tetracycline absorption',
                'usage_instructions' => 'Take with food for better absorption; take at same time daily',
                'food_interaction' => 'Take with food for better absorption',
                'alcohol_warning' => 'Limit alcohol; may affect vitamin absorption and metabolism',
            ],
            'mineral_supplement' => [
                'adult_dose' => 'As directed on package or by physician',
                'child_dose' => 'Age-appropriate dosing as directed',
                'max_daily_dose' => 'Varies by specific mineral',
                'duration_recommendation' => 'As directed; long-term if deficiency persists',
                'side_effects' => 'GI upset, constipation (iron, calcium), nausea, metallic taste',
                'contraindications' => 'Hemochromatosis (iron); hypercalcemia (calcium); specific contraindications vary',
                'pregnancy_safe' => 'Safe at recommended doses; iron, calcium, folic acid important during pregnancy',
                'allergy_warning' => 'Rare allergic reactions; some formulations contain allergens',
                'drug_interaction_notes' => 'Calcium, iron, zinc may reduce absorption of tetracyclines, fluoroquinolones; calcium reduces bisphosphonate absorption',
                'usage_instructions' => 'Take with food to reduce GI upset; take 2-3 hours apart from certain medications',
                'food_interaction' => 'Iron: take with vitamin C for absorption; avoid tea/coffee; Calcium: take with food',
                'alcohol_warning' => 'Limit alcohol; may affect mineral absorption and metabolism',
            ],
            'antiviral' => [
                'adult_dose' => 'Varies significantly by specific drug and condition',
                'child_dose' => 'Weight-based dosing; consult physician',
                'max_daily_dose' => 'Varies by specific drug',
                'duration_recommendation' => '5-14 days for acute infections; long-term for chronic conditions',
                'side_effects' => 'Nausea, headache, diarrhea, fatigue, renal impairment (some)',
                'contraindications' => 'Specific contraindications vary by drug; severe renal/hepatic impairment (dose adjustment)',
                'pregnancy_safe' => 'Varies by specific drug; consult physician',
                'allergy_warning' => 'Allergic reactions including rash; report severe skin reactions or breathing difficulty',
                'drug_interaction_notes' => 'Many drug interactions vary by drug; renal dose adjustment often required',
                'usage_instructions' => 'Start as early as possible after symptom onset; complete full course',
                'food_interaction' => 'Check specific drug; some require food, others empty stomach',
                'alcohol_warning' => 'Limit or avoid alcohol; may worsen side effects or hepatotoxicity',
            ],
            'laxative' => [
                'adult_dose' => 'Varies by type; follow package or physician instructions',
                'child_dose' => 'Age-appropriate dosing; consult physician',
                'max_daily_dose' => 'Varies by type; do not exceed recommended dose',
                'duration_recommendation' => 'Short-term use (3-7 days); chronic use requires medical advice',
                'side_effects' => 'Abdominal cramping, bloating, diarrhea, electrolyte imbalances (long-term)',
                'contraindications' => 'GI obstruction; acute abdominal pain; nausea/vomiting; undiagnosed rectal bleeding',
                'pregnancy_safe' => 'Some safe (e.g., lactulose, docusate); consult physician',
                'allergy_warning' => 'Rare allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'May reduce absorption of other medications; separate by 2+ hours',
                'usage_instructions' => 'Take with plenty of water; may take several hours to work; do not use long-term',
                'food_interaction' => 'Increase fiber and water intake with dietary measures',
                'alcohol_warning' => 'Moderate alcohol acceptable; avoid excessive (dehydration worsens constipation)',
            ],
            'antiparasitic' => [
                'adult_dose' => 'Varies by specific drug and parasite',
                'child_dose' => 'Weight-based dosing; consult physician',
                'max_daily_dose' => 'Varies by specific drug',
                'duration_recommendation' => 'Single dose or 3-14 days depending on parasite',
                'side_effects' => 'Nausea, abdominal pain, headache, dizziness, diarrhea',
                'contraindications' => 'Hypersensitivity; pregnancy (some); severe hepatic impairment',
                'pregnancy_safe' => 'Consult physician; some contraindicated, others safe',
                'allergy_warning' => 'Allergic reactions including rash, pruritus; report severe reactions',
                'drug_interaction_notes' => 'Varies by specific drug; may affect warfarin metabolism',
                'usage_instructions' => 'Take exactly as directed; may repeat dose after 1-2 weeks for some parasites',
                'food_interaction' => 'Some require fatty food for absorption; check specific drug',
                'alcohol_warning' => 'Avoid alcohol; possible disulfiram-like reaction with some',
            ],
            'expectorant_mucolytic' => [
                'adult_dose' => '200-400 mg every 6-8 hours',
                'child_dose' => 'Age-appropriate dosing; consult package',
                'max_daily_dose' => '2400 mg (varies by specific drug)',
                'duration_recommendation' => '5-7 days or as directed',
                'side_effects' => 'Nausea, vomiting, diarrhea, stomach pain, dizziness',
                'contraindications' => 'Hypersensitivity; caution in peptic ulcer (mucolytics)',
                'pregnancy_safe' => 'Generally safe; consult physician',
                'allergy_warning' => 'Rare allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Few significant interactions; may increase cough suppressant effect',
                'usage_instructions' => 'Take with plenty of water to help loosen mucus',
                'food_interaction' => 'Take with food if stomach upset occurs',
                'alcohol_warning' => 'Limit alcohol; may worsen side effects',
            ],
            'cough_suppressant' => [
                'adult_dose' => '10-20 mg every 4-6 hours as needed',
                'child_dose' => 'Age-appropriate dosing; consult physician (not for children under 4 years)',
                'max_daily_dose' => '120 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term use (3-5 days); consult physician if persistent',
                'side_effects' => 'Drowsiness, dizziness, nausea, constipation',
                'contraindications' => 'Respiratory depression; asthma; COPD; caution with MAOIs',
                'pregnancy_safe' => 'Consult physician; avoid in first trimester',
                'allergy_warning' => 'Allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Increased CNS depression with alcohol, sedatives; serotonergic effects with SSRIs, MAOIs (dextromethorphan)',
                'usage_instructions' => 'Use only as needed; do not exceed recommended dose',
                'food_interaction' => 'Can be taken with or without food',
                'alcohol_warning' => 'Avoid alcohol; increased drowsiness and CNS depression',
            ],
            'antigout' => [
                'adult_dose' => '300-600 mg daily (varies by specific drug)',
                'child_dose' => 'Limited use; not typically prescribed',
                'max_daily_dose' => '800 mg (varies by specific drug)',
                'duration_recommendation' => 'Long-term maintenance; continue as directed',
                'side_effects' => 'Nausea, diarrhea, rash, elevated liver enzymes',
                'contraindications' => 'Severe hepatic/renal impairment; caution with bone marrow suppression',
                'pregnancy_safe' => 'Consult physician; avoid unless clearly needed',
                'allergy_warning' => 'Allergic skin reactions including severe (Stevens-Johnson syndrome rare); discontinue if rash',
                'drug_interaction_notes' => 'Many drug interactions; increased toxicity with thiazides, warfarin; decreased effect with NSAIDs',
                'usage_instructions' => 'Take with food to reduce GI upset; maintain adequate hydration',
                'food_interaction' => 'Take with food to minimize GI upset; avoid high-purine foods',
                'alcohol_warning' => 'Avoid alcohol; may increase uric acid levels and trigger flare-ups',
            ],
            'muscle_relaxant' => [
                'adult_dose' => '5-20 mg every 6-8 hours (varies by specific drug)',
                'child_dose' => 'Limited use; weight-based dosing under supervision',
                'max_daily_dose' => '60 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term use (1-2 weeks) for acute muscle spasm',
                'side_effects' => 'Drowsiness, dizziness, dry mouth, fatigue, blurred vision',
                'contraindications' => 'Myasthenia gravis; hypersensitivity; caution in hepatic impairment',
                'pregnancy_safe' => 'Consult physician; avoid unless clearly needed',
                'allergy_warning' => 'Allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Increased CNS depression with alcohol, benzodiazepines, opioids; may potentiate MAOIs',
                'usage_instructions' => 'May cause drowsiness; avoid driving; take with food if GI upset',
                'food_interaction' => 'Take with food to reduce GI upset',
                'alcohol_warning' => 'Avoid alcohol; increased drowsiness and CNS depression',
            ],
            'thyroid' => [
                'adult_dose' => '25-200 mcg daily (varies by specific drug and condition)',
                'child_dose' => 'Weight-based dosing; endocrinology supervision required',
                'max_daily_dose' => 'Varies by individual needs; determined by thyroid function tests',
                'duration_recommendation' => 'Long-term replacement therapy; continue as directed',
                'side_effects' => 'Palpitations, sweating, anxiety, weight loss, insomnia (if over-treated)',
                'contraindications' => 'Untreated adrenal insufficiency; thyrotoxicosis; recent MI',
                'pregnancy_safe' => 'Essential during pregnancy; dose adjustment needed; consult physician',
                'allergy_warning' => 'Rare allergic reactions; report chest pain, rapid heartbeat, excessive sweating',
                'drug_interaction_notes' => 'May increase warfarin effect; decreased absorption with calcium, iron supplements; affects antidiabetic control',
                'usage_instructions' => 'Take on empty stomach 30-60 minutes before breakfast; same time daily; do not switch brands without consulting',
                'food_interaction' => 'Take on empty stomach; avoid soy, high-fiber foods, walnuts within 1-2 hours of dose',
                'alcohol_warning' => 'Moderate alcohol generally acceptable; monitor thyroid function',
            ],
            'erectile_dysfunction' => [
                'adult_dose' => '25-100 mg as needed 1 hour before sexual activity (varies by specific drug)',
                'child_dose' => 'Not applicable',
                'max_daily_dose' => '100 mg once daily (varies by specific drug)',
                'duration_recommendation' => 'As needed; not for continuous use without medical assessment',
                'side_effects' => 'Headache, flushing, dyspepsia, nasal congestion, visual changes, back pain',
                'contraindications' => 'Concurrent nitrates (fatal hypotension); severe hepatic/renal impairment; recent stroke/MI; hypotension',
                'pregnancy_safe' => 'Not indicated for use in women',
                'allergy_warning' => 'Allergic reactions including rash, urticaria; sudden vision or hearing loss (rare)',
                'drug_interaction_notes' => 'Do not use with nitrates (any form); increased hypotension with alpha-blockers; avoid grapefruit juice',
                'usage_instructions' => 'Take 30-60 minutes before sexual activity; do not exceed once daily; avoid high-fat meal before dose',
                'food_interaction' => 'Avoid grapefruit juice; high-fat meals delay absorption',
                'alcohol_warning' => 'Limit alcohol; may reduce effectiveness and increase side effects',
            ],
            'antiparkinson' => [
                'adult_dose' => 'Varies by specific drug; levodopa: 300-2000 mg daily in divided doses',
                'child_dose' => 'Not typically prescribed in children',
                'max_daily_dose' => 'Varies by specific drug',
                'duration_recommendation' => 'Long-term maintenance; do not discontinue abruptly',
                'side_effects' => 'Nausea, dizziness, dyskinesias, hallucinations, confusion, dry mouth',
                'contraindications' => 'Narrow-angle glaucoma; melanoma (levodopa); severe psychosis; MAOI use',
                'pregnancy_safe' => 'Consult physician; use if clearly needed',
                'allergy_warning' => 'Rare allergic reactions; report involuntary movements, mood changes',
                'drug_interaction_notes' => 'Avoid with high-protein meals (levodopa absorption); increased side effects with MAOIs, antipsychotics; avoid pyridoxine with levodopa alone',
                'usage_instructions' => 'Take at same times daily; be consistent with meal timing; do not stop abruptly',
                'food_interaction' => 'Levodopa: avoid high-protein meals near dosing; can take with food to reduce nausea',
                'alcohol_warning' => 'Limit alcohol; may worsen parkinsonian symptoms and increase side effects',
            ],
            'antidiarrheal' => [
                'adult_dose' => '2-4 mg after each loose stool, max 16 mg/day (varies by specific drug)',
                'child_dose' => 'Age-appropriate dosing; consult physician',
                'max_daily_dose' => '16 mg (varies by specific drug)',
                'duration_recommendation' => 'Short-term use (1-2 days); consult physician if persistent',
                'side_effects' => 'Constipation, dizziness, drowsiness, dry mouth, nausea',
                'contraindications' => 'Dysentery (blood in stool); active ulcerative colitis; bacterial enterocolitis; GI obstruction',
                'pregnancy_safe' => 'Generally safe; consult physician',
                'allergy_warning' => 'Rare allergic reactions including rash, urticaria',
                'drug_interaction_notes' => 'Increased CNS depression with alcohol, sedatives; may affect absorption of other medications',
                'usage_instructions' => 'Take after each loose stool; maintain adequate fluid and electrolyte intake',
                'food_interaction' => 'Avoid spicy, fatty foods; eat bland diet (BRAT diet recommended)',
                'alcohol_warning' => 'Avoid alcohol; may worsen diarrhea and dehydration',
            ],
            'general' => [
                'adult_dose' => 'As directed by physician',
                'child_dose' => 'As directed by physician',
                'max_daily_dose' => 'As directed by physician',
                'duration_recommendation' => 'As directed by physician',
                'side_effects' => 'Consult your physician for specific side effect profile',
                'contraindications' => 'Consult your physician for specific contraindications',
                'pregnancy_safe' => 'Consult physician before use during pregnancy or breastfeeding',
                'allergy_warning' => 'Seek immediate medical help if signs of allergic reaction occur',
                'drug_interaction_notes' => 'Consult your physician or pharmacist about potential drug interactions',
                'usage_instructions' => 'Take exactly as prescribed; do not exceed recommended dose',
                'food_interaction' => 'Consult your physician about food interactions',
                'alcohol_warning' => 'Consult your physician about alcohol use during treatment',
            ],
        ];
    }

    protected function loadKeywordMap(): array
    {
        return [
            // Antibiotics - Penicillins
            'amoxicillin' => ['antibiotic'],
            'ampicillin' => ['antibiotic'],
            'cloxacillin' => ['antibiotic'],
            'flucloxacillin' => ['antibiotic'],
            'penicillin' => ['antibiotic'],
            'piperacillin' => ['antibiotic'],
            'co-amoxiclav' => ['antibiotic'],
            'sultamicillin' => ['antibiotic'],
            'pivmecillinam' => ['antibiotic'],
            'ticarcillin' => ['antibiotic'],
            // Antibiotics - Cephalosporins
            'cephradine' => ['antibiotic', 'cephalosporin'],
            'cephalexin' => ['antibiotic', 'cephalosporin'],
            'cefadroxil' => ['antibiotic', 'cephalosporin'],
            'cefuroxime' => ['antibiotic', 'cephalosporin'],
            'cefixime' => ['antibiotic', 'cephalosporin'],
            'ceftriaxone' => ['antibiotic', 'cephalosporin'],
            'cefotaxime' => ['antibiotic', 'cephalosporin'],
            'ceftazidime' => ['antibiotic', 'cephalosporin'],
            'cefepime' => ['antibiotic', 'cephalosporin'],
            'cefoperazone' => ['antibiotic', 'cephalosporin'],
            'cefpodoxime' => ['antibiotic', 'cephalosporin'],
            'cefdinir' => ['antibiotic', 'cephalosporin'],
            'cefprozil' => ['antibiotic', 'cephalosporin'],
            'cefalexin' => ['antibiotic', 'cephalosporin'],
            'cefaclor' => ['antibiotic', 'cephalosporin'],
            'ceftibuten' => ['antibiotic', 'cephalosporin'],
            'cefalotin' => ['antibiotic', 'cephalosporin'],
            // Antibiotics - Fluoroquinolones
            'ciprofloxacin' => ['antibiotic', 'fluoroquinolone'],
            'levofloxacin' => ['antibiotic', 'fluoroquinolone'],
            'moxifloxacin' => ['antibiotic', 'fluoroquinolone'],
            'ofloxacin' => ['antibiotic', 'fluoroquinolone'],
            'norfloxacin' => ['antibiotic', 'fluoroquinolone'],
            'gatifloxacin' => ['antibiotic', 'fluoroquinolone'],
            'sparfloxacin' => ['antibiotic', 'fluoroquinolone'],
            'pefloxacin' => ['antibiotic', 'fluoroquinolone'],
            'nalidixic' => ['antibiotic', 'fluoroquinolone'],
            // Antibiotics - Macrolides
            'azithromycin' => ['antibiotic', 'macrolide'],
            'erythromycin' => ['antibiotic', 'macrolide'],
            'clarithromycin' => ['antibiotic', 'macrolide'],
            'roxithromycin' => ['antibiotic', 'macrolide'],
            'spiramycin' => ['antibiotic', 'macrolide'],
            'fidaxomicin' => ['antibiotic', 'macrolide'],
            // Antibiotics - Aminoglycosides
            'gentamicin' => ['antibiotic', 'aminoglycoside'],
            'amikacin' => ['antibiotic', 'aminoglycoside'],
            'streptomycin' => ['antibiotic', 'aminoglycoside'],
            'neomycin' => ['antibiotic', 'aminoglycoside'],
            'tobramycin' => ['antibiotic', 'aminoglycoside'],
            // Antibiotics - Tetracyclines
            'doxycycline' => ['antibiotic', 'tetracycline'],
            'tetracycline' => ['antibiotic', 'tetracycline'],
            'minocycline' => ['antibiotic', 'tetracycline'],
            'tigecycline' => ['antibiotic', 'tetracycline'],
            // Antibiotics - Others
            'metronidazole' => ['antibiotic'],
            'clindamycin' => ['antibiotic'],
            'cotrimoxazole' => ['antibiotic'],
            'sulfamethoxazole' => ['antibiotic'],
            'trimethoprim' => ['antibiotic'],
            'nitrofurantoin' => ['antibiotic'],
            'vancomycin' => ['antibiotic'],
            'linezolid' => ['antibiotic'],
            'colistin' => ['antibiotic'],
            'chloramphenicol' => ['antibiotic'],
            'fusidic' => ['antibiotic'],
            'mupirocin' => ['antibiotic'],
            'rifampicin' => ['antibiotic'],
            'rifaximin' => ['antibiotic'],
            'daptomycin' => ['antibiotic'],
            'polymyxin' => ['antibiotic'],
            'teicoplanin' => ['antibiotic'],
            'fosfomycin' => ['antibiotic'],
            // Antifungals
            'fluconazole' => ['antifungal'],
            'ketoconazole' => ['antifungal'],
            'itraconazole' => ['antifungal'],
            'terbinafine' => ['antifungal'],
            'clotrimazole' => ['antifungal'],
            'miconazole' => ['antifungal'],
            'nystatin' => ['antifungal'],
            'amphotericin' => ['antifungal'],
            'voriconazole' => ['antifungal'],
            'griseofulvin' => ['antifungal'],
            'caspofungin' => ['antifungal'],
            // PPIs
            'omeprazole' => ['ppi'],
            'esomeprazole' => ['ppi'],
            'pantoprazole' => ['ppi'],
            'rabeprazole' => ['ppi'],
            'lansoprazole' => ['ppi'],
            'dexrabeprazole' => ['ppi'],
            'dexlansoprazole' => ['ppi'],
            // H2 Antagonists
            'ranitidine' => ['h2antagonist'],
            'famotidine' => ['h2antagonist'],
            'cimetidine' => ['h2antagonist'],
            'nizatidine' => ['h2antagonist'],
            // Antacids
            'antacid' => ['antacid'],
            'aluminium' => ['antacid'],
            'magnesium hydroxide' => ['antacid'],
            // Painkillers - NSAIDs
            'ibuprofen' => ['painkiller_nsaid'],
            'diclofenac' => ['painkiller_nsaid'],
            'naproxen' => ['painkiller_nsaid'],
            'indomethacin' => ['painkiller_nsaid'],
            'piroxicam' => ['painkiller_nsaid'],
            'ketorolac' => ['painkiller_nsaid'],
            'mefenamic' => ['painkiller_nsaid'],
            'aceclofenac' => ['painkiller_nsaid'],
            'etoricoxib' => ['painkiller_nsaid'],
            'celecoxib' => ['painkiller_nsaid'],
            'meloxicam' => ['painkiller_nsaid'],
            'lornoxicam' => ['painkiller_nsaid'],
            'flurbiprofen' => ['painkiller_nsaid'],
            'ketoprofen' => ['painkiller_nsaid'],
            'sulindac' => ['painkiller_nsaid'],
            'etodolac' => ['painkiller_nsaid'],
            'nabumetone' => ['painkiller_nsaid'],
            'dexketoprofen' => ['painkiller_nsaid'],
            'diclofenac potassium' => ['painkiller_nsaid'],
            'diclofenac sodium' => ['painkiller_nsaid'],
            // Painkillers - Paracetamol
            'paracetamol' => ['painkiller_paracetamol'],
            'acetaminophen' => ['painkiller_paracetamol'],
            // Opioids
            'morphine' => ['opioid'],
            'codeine' => ['opioid'],
            'pethidine' => ['opioid'],
            'tramadol' => ['opioid'],
            'fentanyl' => ['opioid'],
            'oxycodone' => ['opioid'],
            'buprenorphine' => ['opioid'],
            'pentazocine' => ['opioid'],
            'nalbuphine' => ['opioid'],
            'dihydrocodeine' => ['opioid'],
            // Corticosteroids
            'prednisolone' => ['corticosteroid'],
            'prednisone' => ['corticosteroid'],
            'dexamethasone' => ['corticosteroid'],
            'hydrocortisone' => ['corticosteroid'],
            'betamethasone' => ['corticosteroid'],
            'methylprednisolone' => ['corticosteroid'],
            'triamcinolone' => ['corticosteroid'],
            'budesonide' => ['corticosteroid'],
            'beclomethasone' => ['corticosteroid'],
            'fluticasone' => ['corticosteroid'],
            // Antihistamines
            'cetirizine' => ['antihistamine'],
            'loratadine' => ['antihistamine'],
            'fexofenadine' => ['antihistamine'],
            'desloratadine' => ['antihistamine'],
            'levocetirizine' => ['antihistamine'],
            'diphenhydramine' => ['antihistamine'],
            'promethazine' => ['antihistamine'],
            'chlorpheniramine' => ['antihistamine'],
            'cyproheptadine' => ['antihistamine'],
            'hydroxyzine' => ['antihistamine'],
            'ebastine' => ['antihistamine'],
            'mizolastine' => ['antihistamine'],
            'astemizole' => ['antihistamine'],
            // Antidiabetics - Biguanide
            'metformin' => ['antidiabetic_biguanide'],
            // Antidiabetics - Sulfonylurea
            'glibenclamide' => ['antidiabetic_sulfonylurea'],
            'gliclazide' => ['antidiabetic_sulfonylurea'],
            'glimepiride' => ['antidiabetic_sulfonylurea'],
            'glipizide' => ['antidiabetic_sulfonylurea'],
            'gliquidone' => ['antidiabetic_sulfonylurea'],
            'chlorpropamide' => ['antidiabetic_sulfonylurea'],
            // Antidiabetics - DPP-4
            'sitagliptin' => ['antidiabetic_dpp4'],
            'saxagliptin' => ['antidiabetic_dpp4'],
            'vildagliptin' => ['antidiabetic_dpp4'],
            'linagliptin' => ['antidiabetic_dpp4'],
            // Insulin
            'insulin' => ['antidiabetic_insulin'],
            // Antihypertensives - ACE
            'captopril' => ['antihypertensive_ace'],
            'enalapril' => ['antihypertensive_ace'],
            'lisinopril' => ['antihypertensive_ace'],
            'ramipril' => ['antihypertensive_ace'],
            'perindopril' => ['antihypertensive_ace'],
            'fosinopril' => ['antihypertensive_ace'],
            'quinapril' => ['antihypertensive_ace'],
            'trandolapril' => ['antihypertensive_ace'],
            // Antihypertensives - ARB
            'losartan' => ['antihypertensive_arb'],
            'valsartan' => ['antihypertensive_arb'],
            'irbesartan' => ['antihypertensive_arb'],
            'telmisartan' => ['antihypertensive_arb'],
            'candesartan' => ['antihypertensive_arb'],
            'olmesartan' => ['antihypertensive_arb'],
            'azilsartan' => ['antihypertensive_arb'],
            // Antihypertensives - CCB
            'amlodipine' => ['antihypertensive_ccb'],
            'nifedipine' => ['antihypertensive_ccb'],
            'felodipine' => ['antihypertensive_ccb'],
            'verapamil' => ['antihypertensive_ccb'],
            'diltiazem' => ['antihypertensive_ccb'],
            'nimodipine' => ['antihypertensive_ccb'],
            'lercanidipine' => ['antihypertensive_ccb'],
            'nitrendipine' => ['antihypertensive_ccb'],
            // Beta-blockers
            'atenolol' => ['betablocker'],
            'propranolol' => ['betablocker'],
            'metoprolol' => ['betablocker'],
            'bisoprolol' => ['betablocker'],
            'carvedilol' => ['betablocker'],
            'nebivolol' => ['betablocker'],
            'pindolol' => ['betablocker'],
            'sotalol' => ['betablocker'],
            'timolol' => ['betablocker'],
            'labetalol' => ['betablocker'],
            // Statins
            'atorvastatin' => ['statin'],
            'simvastatin' => ['statin'],
            'rosuvastatin' => ['statin'],
            'pravastatin' => ['statin'],
            'fluvastatin' => ['statin'],
            'lovastatin' => ['statin'],
            'pitavastatin' => ['statin'],
            // Bronchodilators
            'salbutamol' => ['bronchodilator'],
            'terbutaline' => ['bronchodilator'],
            'salmeterol' => ['bronchodilator'],
            'formoterol' => ['bronchodilator'],
            'ipratropium' => ['bronchodilator'],
            'tiotropium' => ['bronchodilator'],
            'theophylline' => ['bronchodilator'],
            'bambuterol' => ['bronchodilator'],
            // Leukotriene
            'montelukast' => ['leukotriene'],
            // Antiepileptics
            'carbamazepine' => ['antiepileptic'],
            'valproate' => ['antiepileptic'],
            'phenytoin' => ['antiepileptic'],
            'phenobarbital' => ['antiepileptic'],
            'gabapentin' => ['antiepileptic'],
            'pregabalin' => ['antiepileptic'],
            'lamotrigine' => ['antiepileptic'],
            'levetiracetam' => ['antiepileptic'],
            'topiramate' => ['antiepileptic'],
            'oxcarbazepine' => ['antiepileptic'],
            'ethosuximide' => ['antiepileptic'],
            'clonazepam' => ['antiepileptic'],
            'vigabatrin' => ['antiepileptic'],
            // Antidepressants - SSRI
            'fluoxetine' => ['antidepressant_ssri'],
            'sertraline' => ['antidepressant_ssri'],
            'citalopram' => ['antidepressant_ssri'],
            'escitalopram' => ['antidepressant_ssri'],
            'paroxetine' => ['antidepressant_ssri'],
            'fluvoxamine' => ['antidepressant_ssri'],
            // Antidepressants - TCA
            'amitriptyline' => ['antidepressant_tca'],
            'nortriptyline' => ['antidepressant_tca'],
            'clomipramine' => ['antidepressant_tca'],
            'imipramine' => ['antidepressant_tca'],
            'doxepin' => ['antidepressant_tca'],
            // Antipsychotics
            'risperidone' => ['antipsychotic'],
            'olanzapine' => ['antipsychotic'],
            'quetiapine' => ['antipsychotic'],
            'haloperidol' => ['antipsychotic'],
            'chlorpromazine' => ['antipsychotic'],
            'aripiprazole' => ['antipsychotic'],
            'clozapine' => ['antipsychotic'],
            'ziprasidone' => ['antipsychotic'],
            'trifluoperazine' => ['antipsychotic'],
            'fluphenazine' => ['antipsychotic'],
            // Benzodiazepines
            'diazepam' => ['benzodiazepine'],
            'lorazepam' => ['benzodiazepine'],
            'alprazolam' => ['benzodiazepine'],
            'clonazepam' => ['benzodiazepine'],
            'midazolam' => ['benzodiazepine'],
            'nitrazepam' => ['benzodiazepine'],
            'oxazepam' => ['benzodiazepine'],
            'bromazepam' => ['benzodiazepine'],
            'chlordiazepoxide' => ['benzodiazepine'],
            // Anticoagulants
            'warfarin' => ['anticoagulant'],
            'heparin' => ['anticoagulant'],
            'rivaroxaban' => ['anticoagulant'],
            'apixaban' => ['anticoagulant'],
            'dabigatran' => ['anticoagulant'],
            'edoxaban' => ['anticoagulant'],
            'enoxaparin' => ['anticoagulant'],
            // Antiplatelets
            'aspirin' => ['antiplatelet'],
            'clopidogrel' => ['antiplatelet'],
            'ticagrelor' => ['antiplatelet'],
            'prasugrel' => ['antiplatelet'],
            'dipyridamole' => ['antiplatelet'],
            // Diuretics
            'furosemide' => ['diuretic'],
            'spironolactone' => ['diuretic'],
            'hydrochlorothiazide' => ['diuretic'],
            'indapamide' => ['diuretic'],
            'bumetanide' => ['diuretic'],
            'torasemide' => ['diuretic'],
            'amiloride' => ['diuretic'],
            'triamterene' => ['diuretic'],
            'chlorthalidone' => ['diuretic'],
            'metolazone' => ['diuretic'],
            // Antiemetics
            'ondansetron' => ['antiemetic'],
            'domperidone' => ['antiemetic'],
            'metoclopramide' => ['antiemetic'],
            'prochlorperazine' => ['antiemetic'],
            'dimenhydrinate' => ['antiemetic'],
            // Antispasmodics
            'hyoscine' => ['antispasmodic'],
            'dicyclomine' => ['antispasmodic'],
            'mebeverine' => ['antispasmodic'],
            'drotaverine' => ['antispasmodic'],
            'alverine' => ['antispasmodic'],
            'pinaverium' => ['antispasmodic'],
            // Vitamins
            'vitamin' => ['vitamin'],
            'multivitamin' => ['vitamin'],
            'vit a' => ['vitamin'],
            'vitamin a' => ['vitamin'],
            'vit b' => ['vitamin'],
            'vitamin b' => ['vitamin'],
            'vitamin b1' => ['vitamin'],
            'vitamin b12' => ['vitamin'],
            'vitamin c' => ['vitamin'],
            'vitamin d' => ['vitamin'],
            'vitamin e' => ['vitamin'],
            'vitamin k' => ['vitamin'],
            'folic acid' => ['vitamin'],
            'calciferol' => ['vitamin'],
            'thiamine' => ['vitamin'],
            'pyridoxine' => ['vitamin'],
            'cyanocobalamin' => ['vitamin'],
            'ascorbic acid' => ['vitamin'],
            'riboflavin' => ['vitamin'],
            'nicotinamide' => ['vitamin'],
            // Minerals
            'calcium' => ['mineral_supplement'],
            'iron' => ['mineral_supplement'],
            'ferrous' => ['mineral_supplement'],
            'zinc' => ['mineral_supplement'],
            'magnesium' => ['mineral_supplement'],
            'potassium' => ['mineral_supplement'],
            'selenium' => ['mineral_supplement'],
            // Antivirals
            'acyclovir' => ['antiviral'],
            'oseltamivir' => ['antiviral'],
            'valacyclovir' => ['antiviral'],
            'ribavirin' => ['antiviral'],
            'tenofovir' => ['antiviral'],
            'lamivudine' => ['antiviral'],
            'zidovudine' => ['antiviral'],
            'efavirenz' => ['antiviral'],
            'nevirapine' => ['antiviral'],
            'lopinavir' => ['antiviral'],
            'ritonavir' => ['antiviral'],
            'sofosbuvir' => ['antiviral'],
            'entecavir' => ['antiviral'],
            'favipiravir' => ['antiviral'],
            'remdesivir' => ['antiviral'],
            'ganciclovir' => ['antiviral'],
            // Laxatives
            'lactulose' => ['laxative'],
            'bisacodyl' => ['laxative'],
            'senna' => ['laxative'],
            'docusate' => ['laxative'],
            'polyethylene glycol' => ['laxative'],
            'psyllium' => ['laxative'],
            'sorbitol' => ['laxative'],
            'glycerin' => ['laxative'],
            // Antiparasitics
            'albendazole' => ['antiparasitic'],
            'mebendazole' => ['antiparasitic'],
            'pyrantel' => ['antiparasitic'],
            'ivermectin' => ['antiparasitic'],
            'praziquantel' => ['antiparasitic'],
            'chloroquine' => ['antiparasitic'],
            'artemether' => ['antiparasitic'],
            'lumefantrine' => ['antiparasitic'],
            'quinine' => ['antiparasitic'],
            'metronidazole' => ['antiparasitic'],
            'tinidazole' => ['antiparasitic'],
            'diethylcarbamazine' => ['antiparasitic'],
            'niclosamide' => ['antiparasitic'],
            // Expectorants/Mucolytics
            'ambroxol' => ['expectorant_mucolytic'],
            'bromhexine' => ['expectorant_mucolytic'],
            'acetylcysteine' => ['expectorant_mucolytic'],
            'guaifenesin' => ['expectorant_mucolytic'],
            'carbocisteine' => ['expectorant_mucolytic'],
            // Cough Suppressants
            'dextromethorphan' => ['cough_suppressant'],
            'pholcodine' => ['cough_suppressant'],
            'butamirate' => ['cough_suppressant'],
            // Antigout
            'allopurinol' => ['antigout'],
            'febuxostat' => ['antigout'],
            'colchicine' => ['antigout'],
            'probenecid' => ['antigout'],
            // Muscle Relaxants
            'baclofen' => ['muscle_relaxant'],
            'tizanidine' => ['muscle_relaxant'],
            'methocarbamol' => ['muscle_relaxant'],
            'carisoprodol' => ['muscle_relaxant'],
            'cyclobenzaprine' => ['muscle_relaxant'],
            'chlorzoxazone' => ['muscle_relaxant'],
            // Thyroid
            'thyroxine' => ['thyroid'],
            'levothyroxine' => ['thyroid'],
            'propylthiouracil' => ['thyroid'],
            'carbimazole' => ['thyroid'],
            'methimazole' => ['thyroid'],
            // Erectile Dysfunction
            'sildenafil' => ['erectile_dysfunction'],
            'tadalafil' => ['erectile_dysfunction'],
            'vardenafil' => ['erectile_dysfunction'],
            // Antiparkinson
            'levodopa' => ['antiparkinson'],
            'carbidopa' => ['antiparkinson'],
            'pramipexole' => ['antiparkinson'],
            'ropinirole' => ['antiparkinson'],
            'selegiline' => ['antiparkinson'],
            'entacapone' => ['antiparkinson'],
            'trihexyphenidyl' => ['antiparkinson'],
            // Antidiarrheals
            'loperamide' => ['antidiarrheal'],
            'racecadotril' => ['antidiarrheal'],
        ];
    }

    protected function loadOverrides(): array
    {
        $path = __DIR__ . '/medicine_overrides.php';
        if (file_exists($path)) {
            return require $path;
        }
        return [];
    }
}
